# This is the main configuration file for the MkDocs website.
# Use hash-comments to comment out pages have not been written
# Reference: http://www.mkdocs.org/user-guide/configuration/
#
site_name: Learn / Excel
nav:
- Home: index.md
- Overview: overview.md
- Data File Import/Export: file-import-export.md
- Web Services: web-services.md
- Time Series: time-series.md
- Charts: charts.md
- Maps: maps.md
- Automation: automation.md
- Resources: resources.md
# ------- configuration properties ---------------
# Alphabetize
# ------------------------------------------------
copyright:  Copyright Open Water Foundation
# Use Material theme
# - installation notes:  https://github.com/squidfunk/mkdocs-material
# ------------------------------------------------
# Use extra CSS to customize styles, based on theme
extra_css:
  - 'css/extra-material-theme.css'
# ------------------------------------------------
# Google Analytics:
# - see:  https://squidfunk.github.io/mkdocs-material/getting-started/#google-analytics
extra:
  analytics:
    provider: google
    property: 'G-KJFMBY739T'
# ------------------------------------------------
site_author:  Open Water Foundation
site_description:  Open Water Foundation Learn Excel
# ------------------------------------------------
# Use Material theme:
# - installation notes:  https://github.com/squidfunk/mkdocs-material
theme:
  name: 'material'
  favicon: 'images/OWF-Logo-Favicon-32x32.png'
